-- Tabela FUNCIONARIO
CREATE TABLE FUNCIONARIO (
  CPF INT PRIMARY KEY,
  NOME VARCHAR(100),
  DATA_NASCIMENTO DATE,
  TELEFONE VARCHAR(20),
  ENDERECO VARCHAR(200)
);

-- Tabela CORRETOR
CREATE TABLE CORRETOR (
  CRECI INT PRIMARY KEY,
  ESPECIALIDADE VARCHAR(100),
  CPF INT REFERENCES FUNCIONARIO(CPF)
);

-- Tabela FUNCIONARIO_ADM
CREATE TABLE FUNCIONARIO_ADM (
  MATRICULA INT PRIMARY KEY,
  CARGO VARCHAR(100),
  CPF INT REFERENCES FUNCIONARIO(CPF)
);

-- Tabela INQUILINO
CREATE TABLE INQUILINO (
  CODIGO_INQ INT PRIMARY KEY,
  ENDERECO VARCHAR(200),
  TELEFONE_1 VARCHAR(20),
  TELEFONE_2 VARCHAR(20),
  EMAIL VARCHAR(100)
);

-- Tabela INQUILINO_PF
CREATE TABLE INQUILINO_PF (
  CPF INT PRIMARY KEY,
  NOME VARCHAR(100),
  CODIGO_INQ INT REFERENCES INQUILINO(CODIGO_INQ)
);

-- Tabela INQUILINO_PJ
CREATE TABLE INQUILINO_PJ (
  CNPJ INT PRIMARY KEY,
  RAZAO_SOCIAL VARCHAR(100),
  CPF_RESP INT,
  NOME_RESP VARCHAR(100),
  CODIGO_INQ INT REFERENCES INQUILINO(CODIGO_INQ)
);

-- Tabela ATENDIMENTO
CREATE TABLE ATENDIMENTO (
  CRECI INT REFERENCES CORRETOR(CRECI),
  COD_INQ INT REFERENCES INQUILINO(CODIGO_INQ),
  PRIMARY KEY (CRECI, COD_INQ)
);

-- Tabela PROPRIETARIO
CREATE TABLE PROPRIETARIO (
  CODIGO_PROP INT PRIMARY KEY,
  ENDERECO VARCHAR(200),
  TELEFONE_1 VARCHAR(20),
  TELEFONE_2 VARCHAR(20),
  EMAIL VARCHAR(100)
);

-- Tabela PROPRIETARIO_PF
CREATE TABLE PROPRIETARIO_PF (
  CPF INT PRIMARY KEY,
  NOME VARCHAR(100),
  CODIGO_PROP INT REFERENCES PROPRIETARIO(CODIGO_PROP)
);

-- Tabela PROPRIETARIO_PJ
CREATE TABLE PROPRIETARIO_PJ (
  CNPJ INT PRIMARY KEY,
  RAZAO_SOCIAL VARCHAR(100),
  CPF_RESP INT,
  NOME_RESP VARCHAR(100),
  CODIGO_PROP INT REFERENCES PROPRIETARIO(CODIGO_PROP)
);

-- Tabela CONDOMINIO
CREATE TABLE CONDOMINIO (
  CODIGO_COND INT PRIMARY KEY,
  NOME VARCHAR(100),
  ADMINISTRADORA VARCHAR(100),
  TELEFONE VARCHAR(20),
  EMAIL VARCHAR(100)
);

-- Tabela IMOVEL
CREATE TABLE IMOVEL (
  CODIGO_IM INT PRIMARY KEY,
  ENDERECO VARCHAR(200),
  IPTU INT,
  COD_PROP INT REFERENCES PROPRIETARIO(CODIGO_PROP),
  COD_COND INT REFERENCES CONDOMINIO(CODIGO_COND)
);

-- Tabela ALUGUEL
CREATE TABLE ALUGUEL (
  ID_CONTRATO INT PRIMARY KEY,
  CRECI_CORRETOR INT REFERENCES CORRETOR(CRECI),
  DATA_INICIO DATE,
  DATA_FIM DATE,
  VALOR DECIMAL(10, 2),
  GARANTIA TEXT,
  COD_INQ INT REFERENCES INQUILINO(CODIGO_INQ),
  COD_IM INT REFERENCES IMOVEL(CODIGO_IM)
);

-- Tabela PAGAMENTOS
CREATE TABLE PAGAMENTOS (
  ID_CONTRATO INT REFERENCES ALUGUEL(ID_CONTRATO),
  DATA_VENCIMENTO DATE,
  DATA_PAGAMENTO DATE,
  VALOR_PAGO DECIMAL(10, 2),
  PRIMARY KEY (ID_CONTRATO, DATA_VENCIMENTO)
);

-- Tabela PRESTADOR_SERVICO
CREATE TABLE PRESTADOR_SERVICO (
  CPF INT PRIMARY KEY,
  NOME VARCHAR(100),
  ESPECIALIDADE VARCHAR(100)
);

-- Tabela MANUTENCAO
CREATE TABLE MANUTENCAO (
  COD_MANUT INT PRIMARY KEY,
  TITULO VARCHAR(100),
  DESCRICAO TEXT,
  DATA DATE,
  VALOR DECIMAL(10, 2),
  COD_IM INT REFERENCES IMOVEL(CODIGO_IM),
  CPF INT REFERENCES PRESTADOR_SERVICO(CPF),
  MATRICULA INT REFERENCES FUNCIONARIO_ADM(MATRICULA)
);

