/*
FUNCIONARIO (CPF, NOME, DATA_NASCIMENTO, TELEFONE, ENDERECO)
	PK (CPF)

CORRETOR (CRECI, ESPECIALIDADE, CPF)
	PK (CRECI)
	FK (CPF) REFERENCIA FUNCIONARIO (CPF)

FUNCIONARIO_ADM (MATRICULA, CARGO, CPF)
	PK (MATRICULA)
	FK (CPF) REFERENCIA FUNCIONARIO (CPF)
	
INQUILINO (CODIGO_INQ, ENDEREÇO, TELEFONE_1, TELEFONE_2, EMAIL)
	PK (CODIGO_INQ)

INQUILINO_PF (CPF, NOME, CODIGO_INQ)
	PK (CPF)
	FK (CODIGO_INQ) REFERENCIA INQUILINO (CODIGO_INQ)

INQUILINO_PJ (CNPJ, RAZAO_SOCIAL, CPF_RESP, NOME_RESP, CODIGO_INQ)
	PK (CNPJ)
	FK (CODIGO_INQ) REFERENCIA INQUILINO (CODIGO_INQ)

ATENDIMENTO (CRECI, COD_INQ)
	PK (CRECI, COD_INQ)
	FK (CRECI) REFERENCIA CORRETOR (CRECI)
	FK (CODIGO_INQ) REFERENCIA INQUILINO (CODIGO_INQ)

PROPRIETARIO (CODIGO_PROP, ENDEREÇO, TELEFONE_1, TELEFONE_2, EMAIL)
	PK (CODIGO_PROP)

PROPRIETARIO_PF (CPF, NOME, CODIGO_PROP)
	PK (CPF)
	FK (CODIGO_PROP) REFERENCIA PROPRIETARIO (CODIGO_PROP)

PROPRIETARIO_PJ (CNPJ, RAZAO_SOCIAL, CPF_RESP, NOME_RESP, CODIGO_PROP)
	PK (CNPJ)
	FK (CODIGO_PROP) REFERENCIA PROPRIETARIO (CODIGO_PROP)

CONDOMINIO (CODIGO_COND, NOME, ADMINISTRADORA, TELEFONE, EMAIL)
	PK (CODIGO_COND)

IMOVEL (CODIGO_IM, ENDERECO, IPTU, COD_PROP, COD_COND)
	PK (CODIGO_IM)
	FK (CODIGO_PROP) REFERENCIA PROPRIETARIO (CODIGO_PROP)
FK (CODIGO_COND) REFERENCIA CONDOMINIO (CODIGO_COND)

ALUGUEL (ID_CONTRATO, CRECI_CORRETOR, DATA_INICIO, DATA_FIM, VALOR, GARANTIA, COD_INQ, COD_IM)
	PK (ID_CONTRATO)
	FK (COD_INQ) REFERENCIA INQUILINO (COD_INQ)
	FK (COD_IM) REFERENCIA IMOVEL (CODIGO_IM)
	FK (CRECI_CORRETOR) REFERENCIA CORRETOR (CRECI)

PAGAMENTOS (ID_CONTRATO, DATA_VENCIMENTO, DATA_PAGAMENTO, VALOR_PAGO)
	PK (ID_CONTRATO, DATA_VENCIMENTO)
	FK (ID_CONTRATO) REFERENCIA ALUGUEL (ID_CONTRATO)

PRESTADOR_SERVICO (CPF, NOME, ESPECIALIDADE)
	PK (CPF)

MANUTENCAO (COD_MANUT, TITULO, DESCRICAO, DATA, VALOR, COD_IM, CPF, MATRICULA)
	PK (COD_MANUT)
	FK (COD_IM) REFERENCIA IMOVEL (CODIGO_IM)
	FK (CPF) REFERENCIA PRESATADOR_SERVICO (CPF)
	FK (MATRICULA) REFERENCIA FUNCIONARIO_ADM (MATRICULA)
*/
